title: Codatory's Scribbles
email: hello@codatory.com
description: >-
  Codatory's notes and scribbles over time
url: https://www.codatory.page
twitter_username: codatory
github_username:  codatory
markdown: GFM
timezone: America/New_York

# Build settings
remote_theme: pages-themes/primer@v0.6.0
plugins:
  - jekyll-feed
  - jekyll-remote-theme

exclude:
  - .sass-cache/
  - .jekyll-cache/
  - .tool-versions
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
